### ISSUE TITLE
Anchor tags don't work in md titles with spaces 

### ISSUE THREAD

**Issue by perspicacious-one** [sarasate/gate_bak#5]
This is a pretty simple issue that can be fixed by adjusting 2 loc. If your markdown titles have spaces, the associated anchor tags don't work. I'm sure there could be a more robust solution but i implemented a simple fix in these files that worked.
**sidebar.js :**
change
```href={`#${element.value.toLowerCase()}```
to
```href={`#${element.value.toLowerCase().split(' ').join('-')}```

**node-renderer.js :**
change
 ```node.children[0].value.toLowerCase()```
to 
```node.children[0].value.toLowerCase().split(' ').join('-')```

**Comment by sarasate** [comment]
@perspicacious-one  Thanks, I haven't tested that. Happy to merge it as a PR if you like. Seems to be a good enough solution for now.

**Comment by SkelegonDK** [comment]
I made a similar solution with replace
``href={#${element.value.replace(/ /g,'-').toLowerCase()}``

**Comment by sarasate** [comment]
Introduced the first solution as not using regexes is usually saver.
